#!/bin/bash

# === Gather data into variables ===

HOSTNAME_VAL=$(hostname)
USERNAME_VAL=$(logname 2>/dev/null || who am i | awk '{print $1}')
DATETIME_VAL=$(date "+%Y-%m-%d %H:%M:%S")

# OS name and version
source /etc/os-release
OS_VAL="$PRETTY_NAME"

# Uptime (human readable)
UPTIME_VAL=$(uptime -p)

# CPU make/model
CPU_VAL=$(grep -m1 "model name" /proc/cpuinfo | cut -d: -f2 | sed 's/^ //')

# RAM total
RAM_VAL=$(free -h | awk '/^Mem:/ {print $2}')

# Disk(s): make, model, and size
DISKS_VAL=$(lshw -class disk 2>/dev/null \
  | awk '/product:/{prod=$2} /size:/{size=$2} /\*-disk/{if(prod && size) print prod" ("size")"; prod=""; size=""}
         END{if(prod && size) print prod" ("size")"}' \
  | paste -sd ', ')
if [ -z "$DISKS_VAL" ]; then
  DISKS_VAL=$(lsblk -dno NAME,SIZE,MODEL 2>/dev/null \
    | awk '{print $3" "$1" ("$2")"}' | paste -sd ', ')
fi

# Video card
VIDEO_VAL=$(lshw -class display 2>/dev/null \
  | awk '/product:/{print $2; exit}')
[ -z "$VIDEO_VAL" ] && VIDEO_VAL="N/A"

# Host IP (interface on default gateway)
GW_IFACE=$(ip r | awk '/^default/ {print $5; exit}')
HOST_ADDR=$(ip -o -4 addr show dev "$GW_IFACE" 2>/dev/null \
  | awk '{print $4}' | cut -d/ -f1 | head -1)

# Default gateway
GATEWAY_VAL=$(ip r | awk '/^default/ {print $3; exit}')

# DNS server
DNS_VAL=$(awk '/^nameserver/ {print $2; exit}' /etc/resolv.conf)

# === Status section ===

# Users logged in
USERS_VAL=$(who | awk '{print $1}' | sort -u | paste -sd ', ')
[ -z "$USERS_VAL" ] && USERS_VAL="none"

# Free disk space for local filesystems
DISK_SPACE_VAL=$(df -h --output=target,avail -x tmpfs -x devtmpfs 2>/dev/null \
  | tail -n +2 \
  | awk '{printf "%s %s  ", $1, $2}' \
  | sed 's/  $//')

# Process count
PROC_COUNT=$(ps aux --no-headers 2>/dev/null | wc -l)

# Load averages
LOAD_VAL=$(uptime | awk -F'load average:' '{print $2}' | sed 's/^ //')

# Listening network ports
PORTS_VAL=$(ss -tlnp 2>/dev/null \
  | awk 'NR>1 {print $4}' \
  | awk -F: '{print $NF}' \
  | sort -un \
  | tr '\n' ',' \
  | sed 's/,$//')

# UFW status
UFW_VAL=$(sudo ufw status 2>/dev/null | awk 'NR==1 {print $2}')
[ -z "$UFW_VAL" ] && UFW_VAL="unknown"

# === Print report ===

cat <<EOF

System Report for $HOSTNAME_VAL generated by $USERNAME_VAL, on $DATETIME_VAL

System Information
------------------
OS:              $OS_VAL
Uptime:          $UPTIME_VAL
CPU:             $CPU_VAL
RAM:             $RAM_VAL
Disk(s):         $DISKS_VAL
Video:           $VIDEO_VAL
Host Address:    $HOST_ADDR
Gateway IP:      $GATEWAY_VAL
DNS Server:      $DNS_VAL

System Status
-------------
Users Logged In: $USERS_VAL
Disk Space:      $DISK_SPACE_VAL
Process Count:   $PROC_COUNT
Load Averages:   $LOAD_VAL
Listening Ports: $PORTS_VAL
UFW Status:      $UFW_VAL

EOF
