#!/bin/bash

# --- GATHER DATA ---
HOSTNAME=$(hostname)
CURRENT_USER=$USER
DATE_TIME=$(date "+%Y-%m-%d %H:%M")

source /etc/os-release
OS=$PRETTY_NAME
UPTIME=$(uptime -p)
CPU=$(lscpu | grep "Model name" | sed 's/Model name: *//')
RAM=$(free -h | awk '/^Mem:/ {print $2}')
DISKS=$(lsblk -d -o MODEL,SIZE | grep -v "MODEL" | sed 's/^ *//')
VIDEO=$(lspci | grep -i vga | cut -d ':' -f 3 | sed 's/^ //')
IP_ADDRESS=$(hostname -I | awk '{print $1}')
GATEWAY=$(ip r | grep default | awk '{print $3}')
DNS_SERVER=$(grep "nameserver" /etc/resolv.conf | awk '{print $2}' | head -n 1)

LOGGED_USERS=$(who | awk '{print $1}' | sort | uniq | paste -sd "," -)
DISK_SPACE=$(df -h --output=target,avail | grep "^/" | awk '{print $1 " " $2}' | paste -sd ", " -)
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVG=$(uptime | awk -F'load average:' '{ print $2 }' | sed 's/^ //')
PORTS=$(ss -tuln | grep LISTEN | awk '{print $5}' | cut -d':' -f2 | sort -nu | paste -sd "," -)
UFW_STATUS=$(sudo ufw status | head -n 1 | cut -d ':' -f 2)

# --- OUTPUT ---
cat << EOF

System Report for $HOSTNAME generated by $CURRENT_USER, on $DATE_TIME

System Information
------------------
OS: $OS
Uptime: $UPTIME
CPU: $CPU
RAM: $RAM
Disk(s): $DISKS
Video: $VIDEO
Host Address: $IP_ADDRESS
Gateway IP: $GATEWAY
DNS Server: $DNS_SERVER

System Status
-------------
Users Logged In: $LOGGED_USERS
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVG
Listening Network Ports: $PORTS
UFW Status: $UFW_STATUS

EOF
